#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

require_once ('config/php.php');
require_once ('config/constants.php');
require_once ("config/inserts.php");

$console = new \engine\Modules\Console\ConsoleHandler(
    new \engine\Modules\Console\Request(),
    new \engine\Modules\Console\Commands()
);
$console->handle();