#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

$console = new \engine\Modules\Console\ConsoleHandler(
    new \engine\Modules\Console\Request(),
    new \engine\Modules\Console\Commands()
);
$console->handle();